#!/usr/bin/env python3
"""Parse BUAA-Engineering-Ethics 题库.txt (+ encoded twin) into bank.js."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent
REPO = ROOT.parent
SRC_DIR = REPO / "BUAA-Engineering-Ethics"
STD_PATH = SRC_DIR / "题库.txt"
ENC_PATH = SRC_DIR / "题库-存在编码问题.txt"
OUT_PATH = ROOT / "bank.js"

SPLIT = "----------------------------------------"
STEM_NUM = re.compile(r"^\d+\.\s*")
OPT_LINE = re.compile(r"^(?:([A-E])|true|false)[\.、．]\s*(.*)$", re.I)
LECTURE = re.compile(r"^第\d+讲")


def parse_file(path: Path, lectures_from_headers: bool) -> list[dict]:
    text = path.read_text(encoding="utf-8")
    items: list[dict] = []
    lecture = ""
    for raw in text.split(SPLIT):
        block = raw.strip()
        if not block or block.startswith("\x1a") or len(block) < 8:
            continue
        lines = [ln.rstrip() for ln in block.splitlines() if ln.strip()]
        if not lines:
            continue
        if lectures_from_headers and LECTURE.match(lines[0]):
            lecture = lines[0].strip()
            lines = lines[1:]
            if not lines:
                continue
        stem_parts: list[str] = []
        options: list[dict] = []
        answer_raw = ""
        for ln in lines:
            t = ln.strip()
            if t.startswith("参考答案"):
                answer_raw = t.split("：", 1)[-1].split(":", 1)[-1].strip()
                continue
            m = OPT_LINE.match(t)
            if m:
                key = (m.group(1) or t.split(".", 1)[0]).strip()
                if key.lower() == "true":
                    key = "true"
                elif key.lower() == "false":
                    key = "false"
                options.append({"k": key, "t": (m.group(2) or "").strip()})
                continue
            if not options:
                stem_parts.append(STEM_NUM.sub("", t))
        stem = "".join(stem_parts).strip()
        if not stem or not answer_raw:
            continue
        items.append({
            "lecture": lecture,
            "stem": stem,
            "options": options,
            "answerRaw": answer_raw,
        })
    return items


def classify(answer_raw: str, options: list[dict]) -> tuple[str, list[str], list[str]]:
    raw = answer_raw.replace(" ", "")
    if raw in ("✔", "正确"):
        return "judge", ["true"], ["正确"]
    if raw in ("❌", "错误"):
        return "judge", ["false"], ["错误"]
    keys = [p.strip() for p in re.split(r"[,，、]", answer_raw) if p.strip()]
    by_key = {o["k"]: o["t"] for o in options}
    texts = [by_key[k] for k in keys if k in by_key]
    qtype = "multi" if len(keys) > 1 else "single"
    return qtype, keys, texts


def main() -> None:
    std = parse_file(STD_PATH, lectures_from_headers=True)
    enc = parse_file(ENC_PATH, lectures_from_headers=False)
    if len(std) != 303:
        raise SystemExit(f"expected 303 standard items, got {len(std)}")
    bank = []
    for i, item in enumerate(std):
        qtype, keys, texts = classify(item["answerRaw"], item["options"])
        alts = []
        if i < len(enc):
            alt = enc[i]["stem"]
            if alt and alt != item["stem"]:
                alts.append(alt)
        bank.append({
            "i": i + 1,
            "lec": item["lecture"],
            "no": i + 1,  # overwritten below per-lecture
            "type": qtype,
            "stem": item["stem"],
            "alts": alts,
            "opts": item["options"],
            "ans": keys,
            "ansT": texts,
        })

    # per-lecture numbering matching the txt file
    counts: dict[str, int] = {}
    for q in bank:
        lec = q["lec"]
        counts[lec] = counts.get(lec, 0) + 1
        q["no"] = counts[lec]

    OUT_PATH.write_text(
        "/* generated by build-bank.py — do not edit by hand */\n"
        "window.__YKT_ANSWER_BANK__ = "
        + json.dumps(bank, ensure_ascii=False, separators=(",", ":"))
        + ";\n",
        encoding="utf-8",
    )
    print(f"wrote {OUT_PATH.name}: {len(bank)} questions, {OUT_PATH.stat().st_size} bytes")
    print("lectures:", ", ".join(f"{k}={v}" for k, v in counts.items()))


if __name__ == "__main__":
    main()
